<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="plants.About"  EnableEventValidation="false" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Тут вы можете выбрать растения</h2>
    <h3>Наш ассортимент:</h3>
    
    <h3>Фильтры:
         <asp:DropDownList ID="DropDownList1" Visible="true" AutoPostBack="false" AppendDataBoundItems="true" runat="server">
        </asp:DropDownList>
        <asp:DropDownList ID="DropDownList2" Visible="true" AutoPostBack="false"  AppendDataBoundItems="true" runat="server">
        </asp:DropDownList>
        <asp:DropDownList ID="DropDownList3" Visible="true" AutoPostBack="false"  AppendDataBoundItems="true" runat="server">
        </asp:DropDownList>
        <asp:DropDownList ID="DropDownList4" Visible="true" AutoPostBack="false"  AppendDataBoundItems="true" runat="server">
        </asp:DropDownList>
        <asp:Button ID="Button2" runat="server" Text="Применить" OnClick="Button2_Click" />
    </h3>
        
    <br/>

   
    

   
    <asp:GridView ID="GridView" runat="server"    HeaderStyle-HorizontalAlign="Center"   DataKeyNames="id_plant"   AutoGenerateEditButton="false"  AutoGenerateDeleteButton="false" AllowPaging="false"  AllowSorting="true" AutoGenerateColumns="false" AutoGenerateSelectButton="true"  ShowFooter="false" ShowHeaderWhenEmpty="true" OnSelectedIndexChanged="GridView_SelectedIndexChanged"   
         >
       <HeaderStyle  HorizontalAlign="Center"/>
        <RowStyle HorizontalAlign="Center" />
        
        
         <Columns>
        <asp:TemplateField HeaderText="Введите к-во" >
              <ItemTemplate>
                  <asp:TextBox ID="TextBoxQuantity"  AutoPostBack="false"   OnTextChanged="TextBoxQuantity_TextChanged"  TextMode="Number" Text="1" runat="server" Width="30px"></asp:TextBox>
                          
              </ItemTemplate>
        </asp:TemplateField>
          <asp:TemplateField HeaderText="Название">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("plant_name") %>' runat="server" />
              </ItemTemplate>
              <EditItemTemplate>
                  <asp:TextBox ID="txtPlant"  Text='<%# Eval("plant_name") %>' runat="server"/>
              </EditItemTemplate>
              <FooterTemplate>
                   <asp:TextBox ID="txtPlantFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>
            <asp:TemplateField HeaderText="Цена">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("plant_price") %>' runat="server" />
              </ItemTemplate>
              <EditItemTemplate>
                  <asp:TextBox ID="txtPrice"  Text='<%# Eval("plant_price") %>' runat="server"/>
              </EditItemTemplate>
              <FooterTemplate>
                   <asp:TextBox ID="txtPriceFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>

             <asp:TemplateField HeaderText="Доступно">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("plant_quantity") %>' runat="server" />
              </ItemTemplate>
              <EditItemTemplate>
                  <asp:TextBox ID="txtQuan"  Text='<%# Eval("plant_quantity") %>' runat="server"/>
              </EditItemTemplate>
              <FooterTemplate>
                   <asp:TextBox ID="txtQuanFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>
          <asp:TemplateField   HeaderText="Грунт" >
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("ground_type") %>' runat="server" />
              </ItemTemplate>
             
              <FooterTemplate>
                   <asp:TextBox ID="txtGroundFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField HeaderText="Страна">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("country_name") %>' runat="server" />
              </ItemTemplate>
             
              <FooterTemplate>
                   <asp:TextBox ID="txtCountryFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>
               
          <asp:TemplateField HeaderText="Тип">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("type_name") %>' runat="server" />
              </ItemTemplate>
              
              <FooterTemplate>
                   <asp:TextBox ID="txtTypeFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>
          
          <asp:TemplateField HeaderText="Полив">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("watering_type") %>'   runat="server" />
              </ItemTemplate>
              <FooterTemplate>
                   <asp:TextBox ID="txtWateringFooter" runat="server" />
              </FooterTemplate>
          </asp:TemplateField>
          

          
            

        </Columns>
    
    </asp:GridView>
    <br/>
    <asp:Button ID="ButtonBuy" runat="server"  Text="Заказать"   OnClick="ButtonBuy_Click" />
    <br/>
   
    <asp:Label ID="lblsuccess" Text="" runat="server" ForeColor="Green"></asp:Label>
    <br />
    <asp:Label ID="lblerror" Text="" runat="server" ForeColor="Red"></asp:Label>
    <br />
    <asp:Label ID="Label6" runat="server" Text="Label"></asp:Label>
    <br />
    <asp:Label ID="Label1" Visible="false" runat="server" Text="Ваше имя:"></asp:Label>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:TextBox ID="TextBoxName" Visible="false" runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="Label2" Visible="false" runat="server" Text="Ваша фамилия:"></asp:Label>
    &nbsp;&nbsp;
    <asp:TextBox ID="TextBoxSname" Visible="false" runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="Label4" Visible="false" runat="server" Text="Номер телефона:"></asp:Label>
    <asp:TextBox ID="TextBoxPhone" Visible="false" runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="Label3" Visible="false" runat="server" Text="Город:"></asp:Label>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:DropDownList ID="DropDownListCity" Visible="false" runat="server">
        <asp:ListItem>Kharkiv</asp:ListItem>
        <asp:ListItem>Kiyev</asp:ListItem>
        <asp:ListItem>Odessa</asp:ListItem>
        <asp:ListItem>Lvov</asp:ListItem>
        <asp:ListItem>from office</asp:ListItem>
    </asp:DropDownList>
    <br />
    <asp:Label ID="Label5" Visible="false" runat="server" Text="Комментарий"></asp:Label>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:TextBox ID="TextBoxComment" Visible="false" runat="server"></asp:TextBox>
    
        <br />
    <asp:Button ID="ButtonOk" Visible="false" runat="server" Text="Подтвердить" OnClick="ButtonOk_Click" />
    
        </asp:Content>
