<%@ Page Title="Orders" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Orders.aspx.cs" Inherits="plants.Orders"  EnableEventValidation="false" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
   <br />
    <br />
    <br />
    <asp:GridView ID="GridView" runat="server"    HeaderStyle-HorizontalAlign="Center"   DataKeyNames="id_order"   AutoGenerateEditButton="false"  AutoGenerateDeleteButton="true" OnRowDeleting="GridView_RowDeleting" AllowPaging="false"  AllowSorting="true" AutoGenerateColumns="false" AutoGenerateSelectButton="false"  ShowFooter="false" ShowHeaderWhenEmpty="true"  
        >
         <HeaderStyle  HorizontalAlign="Center"/>
        <RowStyle HorizontalAlign="Center" />
        
         <Columns>
       <asp:TemplateField HeaderText="Номер заказа">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("id_order") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Имя клиента">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("client_name") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Фамилия">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("client_surname") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Телефон">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("client_phone") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Город">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("client_city") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Детали">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("client_notes") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             <asp:TemplateField HeaderText="Растение">
              <ItemTemplate>
                  <asp:Label Text='<%# Eval("plant_name") %>' runat="server" />
             </ItemTemplate>
           </asp:TemplateField>
             </Columns>

        </asp:GridView>
     
    </asp:Content>